[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[project]
name = "rna-gc-bias-metrics"
version = "0.1.1"
description = "A tool to calculate the GC bias profile of RNAseq data."
authors = [{name = "Gautam Naishadham"}]
readme = "README.md"
license-files = ["LICENSE.txt"]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.2",
    "polars>=1.37.1",
    "polars-bio>=0.31",
]

[project.urls]
Homepage = "https://github.com/nebiolabs/rna-gc-bias-metrics"
Source = "https://github.com/nebiolabs/rna-gc-bias-metrics"
Issues = "https://github.com/nebiolabs/rna-gc-bias-metrics/issues"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
